### ISSUE TITLE
Snapshot of current cache items

### ISSUE THREAD

**Issue by inge4pres** [dgraph-io/ristretto#114] opened 2019-12-21 17:58 UTC
Hello there 😄 thanks for developing ristretto!
This is more of a general question rather than a issue: is there a way of creating a persistent snapshot for a running cache?
I've been trying with `gob.NewEncoder(buffer).Encode(cache)` but I have an error `gob: type ristretto.Metrics has no exported fields` which is (apparently) the intended behaviour of gob package ([reference](https://github.com/golang/go/issues/5819)).
Any ideas if this is possible?
Thanks

**Comment by martinmr** [comment] 2020-02-21 19:33
Closing this since it's pretty much a duplicate of #105. If we decide to allow reading a snapshot for a warm startup, we should also enable writing a snapshot of the current items.

The issue with using `gob` is that accessing the unexported fields is not supported by golang. It's most likely using the `reflect` library which has this same limitation.

**Closed** 2020-02-21 19:33 UTC
Labels: kind/enhancement
